import type { Metadata } from "next";
import { ConfigProvider } from "antd";
import "@ant-design/v5-patch-for-react-19";

import Header from "./components/header/page";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col bg-slate-900 text-white justify-center">
        <ConfigProvider
          theme={{
            components: {
              Tabs: {
                itemColor: "#ffffff",
                itemActiveColor: "#00b96b",
                itemSelectedColor: "#00b96b",
                itemHoverColor: "#00b96b",
                inkBarColor: "#00b96b",
              },
            },
          }}
        >
          <Header />
          <div className="flex p-4 w-full justify-center">
            <div className="max-w-screen-2xl">{children}</div>
          </div>
        </ConfigProvider>
      </body>
    </html>
  );
}
